### ISSUE TITLE
Make Drash portable

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#120]
## Summary

What: CI to compile Drash down to JS for portability

Why: Portability is cool.

## Acceptance Criteria

- [ ] add compilation script
- [ ] script runs in CI process
- [ ] script can be used manually

**Comment by alexjamesmalcolm** [comment]
@crookse Would `deno bundle` fit your needs?

**Comment by crookse** [comment]
@alexjamesmalcolm, it would, but we have some `Deno` calls in the codebase and those should be taken out before this becomes a real thing.

**Comment by ebebbington** [comment]
I'll look into it and see if all the `Deno` calls can be replaced and still have the same functionality

**Comment by ebebbington** [comment]
> @alexjamesmalcolm, it would, but we have some `Deno` calls in the codebase and those should be taken out before this becomes a real thing.

I don't think it's possible at this stage, the reading of files can be modified, but there doesn't seem to be an alternative to writing **and appending** to a file without `Deno.write...`. We would also have to use the `--unstable` flag as we are using the `fs` std module.

Along with this, I don't believe a `Reader` interface is exposed outside of `Deno.Reader` (this is used in Drash)

**Comment by ebebbington** [comment]
Actually, it might be doable

@crookse How do you feel about our tests having to use the `--unstable` flag, as well as a user having to use the same flag if they import and use Drash?

**Comment by crookse** [comment]
Using in the tests is fine. Not when importing and using drash

**Comment by ebebbington** [comment]
Fair enough, well because the `fs` std needs the unstable flag, a user will have to use it as well when using Drash. Just waiting until fs no longer needs `--unstable`

FYI for when that happens to whoever works on this:

* all `Deno.readFileSync` can be replaced with `readFileStrSync` from the `fs` module. All tests pass when doing this but i'm not 100% confident everything would work (maybe further tests that run the code might be needed), and these lines of code won't need a decoder. for example:
    ```
    import { readFileStrSync } from "https://deno.land/std@0.53.0/fs/mod.ts"
    // current code
    let html: string = decoder.decode(Deno.readFileSync(this.views_path + template));
    // new code
    let html: string = readFileString(this.views_path + template, { encoding: 'utf-8' })
    ```
* Haven't found an alternative to `Deno.Reader` yet
* Haven't found a way to append data to a file without using `Deno.writeFileSync` yet

**Comment by crookse** [comment]
What we could do to get this somewhat started is take out all the deno calls and export them from a system.ts file. Then if someone wanted to use drash with a different JS runtime or import parts of Drash into their non-Deno project, they can change the Deno calls in system.ts to whatever works for them

**Comment by Guergeiro** [comment]
Why don't we just use the TS compiler? Just need to change the module from `commonjs` to `esnext`. 

This outputs JavaScript files like in the web with the correct `import` statements.

**Comment by ebebbington** [comment]
> Why don't we just use the TS compiler? Just need to change the module from `commonjs` to `esnext`.
> 
> This outputs JavaScript files like in the web with the correct `import` statements.

You mean using `tsc` from NPM?

**Comment by ebebbington** [comment]
Means we'd have to have `node_modules` and `package.json` in a Deno project and Drash 😬 Though Eric might be ok with that idk

**Comment by Guergeiro** [comment]
We don't need. As far as I'm aware, you can install typescript globally and run it. And honestly, I think it should only be done for release versions, that is, have some kind of CI (if possible) to convert it. This means that you can import `mod.ts` or `mod.js`.

Otherwise we would be reinventing the wheel (in a bad way probably).

**Comment by Guergeiro** [comment]
Also I already said to @crookse that I don't see the benefit of doing this but, if we still want to do it, I suggest the use of TypeScript compiler or `deno bundle`.

**Comment by crookse** [comment]
closing. this will be covered by #405
