### ISSUE TITLE
Overall situation  Anomaly capture

### ISSUE THREAD

**Issue by liuxiaobina** [drashland/deno-drash#151]
How to catch the exceptions of the framework? I want to handle the exception information myself

**Comment by crookse** [comment]
Hi @liuxiaobina ,

To do that, you'll have to override `Drash.Http.Server` and create your own implementations of its `run()` and `handleHttpRequestError()` methods. If you want more control, you'll want to create your own implementation of the `handleHttpRequest()` method as well.

It would look something like this:

```typescript
import Drash from "https://deno.land/x/drash@v0.35.0/mod.ts";

class MyCustomServer extends Drash.Http.Server {

  run() { ... }

  handleHttpRequest() { ... }

  handleHttpRequestError() { ... }

}

Drash.Http.Server = MyCustomServer;

const server = new Drash.Http.Server({ ... });

server.run();
```

Please take a look at the following methods' signatures before overriding them so that you don't run into errors:

* [run()](https://github.com/drashland/deno-drash/blob/master/src/http/server.ts#L409)
* [handleHttpRequest()](https://github.com/drashland/deno-drash/blob/master/src/http/server.ts#L191)
* [handleHttpRequestError()](https://github.com/drashland/deno-drash/blob/master/src/http/server.ts#L279)

**Comment by liuxiaobina** [comment]
ok，thank you



---Original---

**Comment by liuxiaobina** [comment]
error TS2540: Cannot assign to 'Server' because it is a read-only property.

► file:///Users/liu/Desktop/deno/app/app.ts:29:12

29 Drash.Http.Server = MyCustomServer;

**Comment by player-4** [comment]
@liuxiaobina, that's happening because of this:

https://github.com/drashland/deno-drash/blob/master/mod.ts#L86

`Server` is a `const`. i can change it to `let` and you should be able to reassign `Server`. stay tuned.

**Comment by player-4** [comment]
@liuxiaobina, i just released `v0.35.1`. pull that down and try reassigning `Drash.Http.Server`.

**Comment by crookse** [comment]
@liuxiaobina,

Did it work?

**Comment by liuxiaobina** [comment]
yes



---Original---

**Comment by crookse** [comment]
Great! Please close this issue if you have no further questions :)

**Comment by liuxiaobina** [comment]
ok. thank you



---Original---
