### ISSUE TITLE
Decorator validation support

### ISSUE THREAD

**Issue by liuxiaobina** [drashland/deno-drash#152]
Whether the framework lacks a verification layer, and whether to consider supporting such writing methods as decorator pattern in the future

**Comment by player-4** [comment]
@liuxiaobina, we don't plan to implement a verification layer. we're leaving that up to users. also, we don't plan to implement a decorator pattern in the future because of the syntax we've chosen for resources--`GET()` = `GET`, `POST()` = `POST`, etc. we're keeping it this way because of semantics.

**Comment by crookse** [comment]
I agree with @player-4. @liuxiaobina, can we close this? Or do you have a use case that you can send us so we can discuss further?

**Comment by crookse** [comment]
So there have been some discussions around decorators in discord. Using decorators for middleware seems to be a good solution. I will be writing that issue today.

**Comment by ebebbington** [comment]
https://github.com/drashland/deno-drash/issues/176

**Comment by player-4** [comment]
decorators were implemented. see #176
