### ISSUE TITLE
LoggerService

### ISSUE THREAD

**Issue by kuhlaid** [drashland/deno-drash#467]
## Summary

https://deno.land/x/drash@v1.3.1/deps.ts#L62 points to a non-existent URI (https://raw.githubusercontent.com/drashland/services/master/logger/logger_service.ts).

**Comment by ebebbington** [comment]
Thanks @kuhlaid, we're aware of this and we will be adding a fix today/tonight, we'll keep this issue updated for when v1.3.2 is released

**Comment by kuhlaid** [comment]
Yeah, I was getting ready to say that tagging a new release should fix things since you have the correction in the master deps.ts file. This is my first day playing around with this module and it looks pretty cool. I will fork the repo so I can continue testing. - thanks

**Comment by ebebbington** [comment]
Ok cool :) We didn't intend on pointing to a master branch, it was left in by accident

If you want to try tackle the issue yourself that's fine. The reason for this issue is because our Services repo made some changes to the `logger_service` file (https://github.com/drashland/services/releases/tag/v0.1.0), so the `import` statement, should really be point to `https://raw.githubusercontent.com/drashland/services/v0.1.0/loggers/console_logger.ts`

**Comment by ebebbington** [comment]
@kuhlaid Try importing v1.4.0, @crookse just released a fix :)

**Comment by kuhlaid** [comment]
Thank you @ebebbington, v1.4.0 imported without issue. - cheers
