### ISSUE TITLE
Accepted response content types config

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#493]
## Summary

What:

Currently in v1, in order to support more content types, the `generateResponse()` method in the `Drash.Http.Response` class has to be overridden. In v2, we should make it so that this is easily configurable so that `Drash.Http.Response` doesn't have to be extended just to support other content types.

Why:

It improves the UX of the API.

## Example Pseudo Code (for implementation)

```typescript

const server = createServer({
  content_types: [
    "application/json",
    "image/png",
    "text/xml",
    "text/html",
    "some/randomthing"
  ]
})

```

**Comment by Guergeiro** [comment]
This is indeed a good feature.

I have some ideas for this, probably for a better API for the user. Instead of creating the server and passing through a config, what do you think of this:

- Server tries it's best to figure out what `Content-Type` the request uri wants. Eg:
  - uri ends with `.html` -> `text/html`
  - uri ends with `.js` -> `text/javascript`
  - uri ends with `.png` -> `image/png`
- The server is not able to figure out, we default to `application/json` or the user explicitly says it wants another type for the resource.

I have somewhat of a [working](https://github.com/drashland/deno-drash/blob/v2/src/resources/concreteProxies/StaticFileResourceProxy.ts#L58) feature that is tied to StaticFiles. We kind of agreed with moving this specific Proxy/Middleware to the Middleware repo, although I can just leave the "figure out" the `Content-Type` logic to behave like that for drash core and only move the StaticFiles to the other repo. Like, just like an [AcceptProxy](https://github.com/drashland/deno-drash/blob/v2/src/resources/concreteProxies/AcceptResourceProxy.ts), we would have a ContentTypeProxy.
What do you think @crookse ?

**Comment by ebebbington** [comment]
closing as:

- we no longer use a default content type
- users are expected to set this themselves (eg use the helper methods to send a response)

**Comment by sanekb** [comment]
Hi

Why was it decided to stop using a default content-type?

I use `response.file()` to serve binaries files that don't have an extension, and as a result I get 500 error (_"Unable to retrieve content type for <file>"_). I can't change the names of these files by adding a _".bin"_ extension to get a generic binary data type.

Should I just use `response.send( 'application/octet-stream', fileBody )` in this case?

Or does it make sense to add a default content-type to the type-selection step in `response.file()` for files without exntension? e.g.
```javascript
// Get the MIME type of the file
const type = mimeTypes.get(extension) ?? 'application/octet-stream';
```

**Comment by ebebbington** [comment]
> Hi
> 
> Why was it decided to stop using a default content-type?
> 
> I use `response.file()` to serve binaries files that don't have an extension, and as a result I get 500 error (_"Unable to retrieve content type for "_). I can't change the names of these files by adding a _".bin"_ extension to get a generic binary data type.
> 
> Should I just use `response.send( 'application/octet-stream', fileBody )` in this case?
> 
> Or does it make sense to add a default content-type to the type-selection step in `response.file()` for files without exntension? e.g.
> 
> ```js
> // Get the MIME type of the file
> const type = mimeTypes.get(extension) ?? 'application/octet-stream';
> ```

The user should be the one to specify it, and there was a lot of boiler plate around it - the way the response API is set up now, you dont usually need a default content type anyways

To solve your issue, you can do
```ts
response.body = Deno.readFileSync("./some_binary_file);
response.headers.set("Content-Type", 'application/pctec-stream');
```
